defmodule Mix.Tasks.Paypal.Provision do
  @moduledoc """
  Creates a PayPal **product**, **monthly** and **annual** subscription **plans**, and a **webhook**
  via the REST API (Sandbox or Live).

  Required env:

    * `PAYPAL_CLIENT_ID`
    * `PAYPAL_CLIENT_SECRET`

  Optional:

    * `PAYPAL_MODE` — `live` (default) or `sandbox`
    * `PAYPAL_WEBHOOK_URL` — listener URL (default `https://rompcrm.com/romp-crm/webhooks/paypal`)
    * `PAYPAL_MONTHLY_PRICE` — default `25.00` USD
    * `PAYPAL_ANNUAL_PRICE` — default `240.00` USD (12× \$20/mo)
    * `PAYPAL_TRIAL_DAYS` — default **`14`** (`0` disables the trial cycle — not recommended for hosted paywall)

  Plans include a **\$0 trial** billing cycle (`TRIAL` tenure) so PayPal collects a payment method but does not charge until the regular cycle begins after the trial.

  Prints IDs to stdout and writes **`deploy/paypal-provision-result.env`** (gitignored) for merging into `.env.production`.

      set -a && source .env.paypal.local && set +a && mix paypal.provision
  """

  use Mix.Task

  @shortdoc "Create PayPal product, subscription plans, and webhook via API"

  @requirements ["app.config"]

  @subscription_events [
    "BILLING.SUBSCRIPTION.ACTIVATED",
    "BILLING.SUBSCRIPTION.CANCELLED",
    "BILLING.SUBSCRIPTION.SUSPENDED",
    "BILLING.SUBSCRIPTION.EXPIRED"
  ]

  def run(_args) do
    _ = Mix.Task.run("app.config")
    {:ok, _} = Application.ensure_all_started(:ssl)
    {:ok, _} = Application.ensure_all_started(:crypto)
    {:ok, _} = Application.ensure_all_started(:req)

    client_id = env!("PAYPAL_CLIENT_ID")
    secret = env!("PAYPAL_CLIENT_SECRET")
    base = api_base()
    monthly = System.get_env("PAYPAL_MONTHLY_PRICE", "25.00")
    annual = System.get_env("PAYPAL_ANNUAL_PRICE", "240.00")
    trial_days = trial_days_from_env()
    webhook_url = webhook_url_default()

    Mix.shell().info("[paypal.provision] API base: #{base}")
    Mix.shell().info("[paypal.provision] trial_days=#{trial_days}")

    with {:ok, token} <- oauth_token(base, client_id, secret),
         {:ok, prod_id} <- create_product(base, token),
         {:ok, monthly_id} <-
           create_plan(base, token, prod_id, "monthly", monthly, trial_days, &billing_cycles_monthly/2),
         {:ok, annual_id} <-
           create_plan(base, token, prod_id, "annual", annual, trial_days, &billing_cycles_yearly/2),
         {:ok, hook_id} <- ensure_webhook(base, token, webhook_url) do
      lines = """
      # Generated by mix paypal.provision — merge into .env.production (do not commit).

      SUBSCRIPTION_PAYWALL_ENABLED=true
      PAYPAL_MODE=#{paypal_mode()}
      PAYPAL_PLAN_MONTHLY_ID=#{monthly_id}
      PAYPAL_PLAN_ANNUAL_ID=#{annual_id}
      PAYPAL_WEBHOOK_ID=#{hook_id}
      PAYPAL_TRIAL_DAYS=#{trial_days}
      """

      out_path = Path.join(File.cwd!(), "deploy/paypal-provision-result.env")
      File.mkdir_p!(Path.dirname(out_path))
      File.write!(out_path, lines)

      Mix.shell().info("\n--- Paste into server env (also saved to #{out_path}) ---\n")
      Mix.shell().info(String.trim_trailing(lines))
      Mix.shell().info("\nWebhook URL registered: #{webhook_url}\n")
      :ok
    else
      {:error, reason} ->
        Mix.shell().error("[paypal.provision] #{inspect(reason)}")
        exit({:shutdown, 1})
    end
  end

  defp env!(key) do
    case System.get_env(key) do
      nil -> Mix.raise("Missing #{key}")
      "" -> Mix.raise("Missing #{key}")
      v -> v
    end
  end

  defp paypal_mode do
    case System.get_env("PAYPAL_MODE", "live") |> String.downcase() do
      "sandbox" -> "sandbox"
      _ -> "live"
    end
  end

  defp api_base do
    if paypal_mode() == "sandbox", do: "https://api-m.sandbox.paypal.com", else: "https://api-m.paypal.com"
  end

  defp webhook_url_default do
    System.get_env("PAYPAL_WEBHOOK_URL") || "https://rompcrm.com/romp-crm/webhooks/paypal"
  end

  defp trial_days_from_env do
    case Integer.parse(System.get_env("PAYPAL_TRIAL_DAYS") || "14") do
      {n, _} when n >= 0 and n <= 365 ->
        n

      _ ->
        Mix.raise("PAYPAL_TRIAL_DAYS must be an integer from 0 to 365")
    end
  end

  defp oauth_token(base, id, secret) do
    auth = Base.encode64("#{id}:#{secret}")

    case Req.post("#{base}/v1/oauth2/token",
           headers: [
             {"authorization", "Basic #{auth}"},
             {"content-type", "application/x-www-form-urlencoded"}
           ],
           body: URI.encode_query(%{"grant_type" => "client_credentials"}),
           decode_body: false
         ) do
      {:ok, %{status: 200, body: raw}} ->
        case json_decode(raw) do
          {:ok, %{"access_token" => tok}} -> {:ok, tok}
          {:ok, other} -> {:error, {:oauth, :bad_body, other}}
          {:error, _} -> {:error, {:oauth, :not_json, raw}}
        end

      {:ok, %{status: code, body: body}} ->
        {:error, {:oauth, code, maybe_json(body)}}

      {:error, err} ->
        {:error, err}
    end
  end

  defp create_product(base, token) do
    body = %{
      "name" => "Romp CRM Hosted Access",
      "description" => "Hosted Romp CRM subscription (includes free trial, then recurring billing)",
      "type" => "SERVICE",
      "category" => "SOFTWARE"
    }

    case Req.post("#{base}/v1/catalogs/products",
           headers: api_headers(token),
           json: body,
           decode_body: false
         ) do
      {:ok, %{status: code, body: raw}} when code in [200, 201] ->
        with {:ok, %{"id" => id}} <- json_decode(raw) do
          Mix.shell().info("[paypal.provision] product id=#{id}")
          {:ok, id}
        else
          _ -> {:error, {:product, :bad_json, raw}}
        end

      {:ok, %{status: code, body: body}} ->
        {:error, {:product, code, maybe_json(body)}}

      {:error, err} ->
        {:error, err}
    end
  end

  defp json_decode(raw) when is_binary(raw), do: Jason.decode(raw)
  defp json_decode(%{} = m), do: {:ok, m}

  defp maybe_json(raw) when is_binary(raw) do
    case Jason.decode(raw) do
      {:ok, m} -> m
      {:error, _} -> raw
    end
  end

  defp maybe_json(other), do: other

  defp billing_cycles_monthly(price, trial_days) do
    trial_cycles(trial_days) ++
      [
        %{
          "frequency" => %{"interval_unit" => "MONTH", "interval_count" => 1},
          "tenure_type" => "REGULAR",
          "sequence" => if(trial_days > 0, do: 2, else: 1),
          "total_cycles" => 0,
          "pricing_scheme" => %{
            "fixed_price" => %{"value" => price, "currency_code" => "USD"}
          }
        }
      ]
  end

  defp billing_cycles_yearly(price, trial_days) do
    trial_cycles(trial_days) ++
      [
        %{
          "frequency" => %{"interval_unit" => "YEAR", "interval_count" => 1},
          "tenure_type" => "REGULAR",
          "sequence" => if(trial_days > 0, do: 2, else: 1),
          "total_cycles" => 0,
          "pricing_scheme" => %{
            "fixed_price" => %{"value" => price, "currency_code" => "USD"}
          }
        }
      ]
  end

  defp trial_cycles(0), do: []

  defp trial_cycles(days) when is_integer(days) and days > 0 do
    [
      %{
        "frequency" => %{"interval_unit" => "DAY", "interval_count" => days},
        "tenure_type" => "TRIAL",
        "sequence" => 1,
        "total_cycles" => 1,
        "pricing_scheme" => %{
          "fixed_price" => %{"value" => "0", "currency_code" => "USD"}
        }
      }
    ]
  end

  defp create_plan(base, token, product_id, label, price_str, trial_days, cycles_fun)
       when is_function(cycles_fun, 2) do
    cycles = cycles_fun.(price_str, trial_days)

    body = %{
      "product_id" => product_id,
      "name" => "Romp CRM — #{label}" <>
        if(trial_days > 0, do: " (#{trial_days}-day trial)", else: ""),
      "description" =>
        "Romp CRM hosted (#{label})" <>
          if(trial_days > 0,
            do: " — #{trial_days}-day free trial then recurring billing",
            else: ""
          ),
      "billing_cycles" => cycles,
      "payment_preferences" => %{
        "auto_bill_outstanding" => true,
        "setup_fee_failure_action" => "CONTINUE",
        "payment_failure_threshold" => 3
      }
    }

    case Req.post("#{base}/v1/billing/plans",
           headers: api_headers(token) ++ [{"prefer", "return=representation"}],
           json: body,
           decode_body: false
         ) do
      {:ok, %{status: code, body: raw}} when code in [200, 201] ->
        with {:ok, %{"id" => id}} <- json_decode(raw) do
          Mix.shell().info("[paypal.provision] plan #{label} id=#{id}")
          {:ok, id}
        else
          _ -> {:error, {:plan, label, :bad_json, raw}}
        end

      {:ok, %{status: code, body: body}} ->
        {:error, {:plan, label, code, maybe_json(body)}}

      {:error, err} ->
        {:error, err}
    end
  end

  defp ensure_webhook(base, token, url) do
    case list_webhooks(base, token) do
      {:ok, hooks} ->
        case Enum.find(hooks, &(&1["url"] == url)) do
          %{"id" => id} ->
            Mix.shell().info("[paypal.provision] reusing existing webhook id=#{id}")
            {:ok, id}

          nil ->
            create_webhook(base, token, url)
        end

      {:error, _} = err ->
        err
    end
  end

  defp list_webhooks(base, token) do
    case Req.get("#{base}/v1/notifications/webhooks",
           headers: api_headers(token),
           decode_body: false
         ) do
      {:ok, %{status: 200, body: raw}} ->
        case json_decode(raw) do
          {:ok, %{"webhooks" => hooks}} -> {:ok, hooks}
          {:ok, other} -> {:error, {:list_webhooks, :bad_shape, other}}
          {:error, _} -> {:error, {:list_webhooks, :bad_json, raw}}
        end

      {:ok, %{status: code, body: body}} ->
        {:error, {:list_webhooks, code, maybe_json(body)}}

      {:error, err} ->
        {:error, err}
    end
  end

  defp create_webhook(base, token, url) do
    body = %{
      "url" => url,
      "event_types" => Enum.map(@subscription_events, &%{"name" => &1})
    }

    case Req.post("#{base}/v1/notifications/webhooks",
           headers: api_headers(token),
           json: body,
           decode_body: false
         ) do
      {:ok, %{status: code, body: raw}} when code in [200, 201] ->
        with {:ok, %{"id" => id}} <- json_decode(raw) do
          Mix.shell().info("[paypal.provision] webhook id=#{id}")
          {:ok, id}
        else
          _ -> {:error, {:webhook, :bad_json, raw}}
        end

      {:ok, %{status: code, body: body}} ->
        {:error, {:webhook, code, maybe_json(body)}}

      {:error, err} ->
        {:error, err}
    end
  end

  defp api_headers(token) do
    [
      {"authorization", "Bearer #{token}"},
      {"content-type", "application/json"}
    ]
  end
end
