import Config

# Configure your database
config :romp_crm, RompCrm.Repo,
  database: Path.expand("../romp_crm_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :romp_crm, RompCrmWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "6tv7ol7HTB4RUH4C+5y9jK46dcdwlTWOC1dQgcIVc1AXunluXa+yZD9DsQ6s7Mkm",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:romp_crm, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:romp_crm, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :romp_crm, RompCrmWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$",
      # Gettext translations
      ~r"priv/gettext/.*\.po$",
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/romp_crm_web/router\.ex$",
      ~r"lib/romp_crm_web/(controllers|live|components)/.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :romp_crm, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Twilio inbound SMS + Anthropic parsing (export env vars before `mix phx.server`)
config :romp_crm,
  twilio_account_sid: System.get_env("TWILIO_ACCOUNT_SID"),
  twilio_auth_token: System.get_env("TWILIO_AUTH_TOKEN"),
  twilio_messaging_from_number:
    (case System.get_env("TWILIO_MESSAGING_FROM") |> to_string() |> String.trim() do
       "" -> "+18022780965"
       s -> s
     end),
  twilio_sms_replies_enabled: System.get_env("TWILIO_SMS_REPLIES_ENABLED") != "false",
  anthropic_api_key: System.get_env("ANTHROPIC_API_KEY"),
  anthropic_model: System.get_env("ANTHROPIC_MODEL") || "claude-sonnet-4-20250514",
  twilio_webhook_public_url: System.get_env("TWILIO_WEBHOOK_PUBLIC_URL"),
  twilio_voice_webhook_public_url: System.get_env("TWILIO_VOICE_WEBHOOK_PUBLIC_URL"),
  twilio_voice_forward_e164:
    (case System.get_env("TWILIO_VOICE_FORWARD_TO") |> to_string() |> String.trim() do
       "" -> "+18024587299"
       s -> s
     end),
  skip_twilio_signature_validation: System.get_env("SKIP_TWILIO_SIGNATURE_VALIDATION") == "true",
  registration_email_allowlist: [
    "151henry151@gmail.com",
    "jvzieger@icloud.com",
    "jzieger2@gmail.com",
    "henry@hromp.com"
  ],
  enforce_registration_allowlist: false,
  twilio_sms_allowed_from_normalized: ["18024587299", "18024582710", "18022780965"]
